name: Deploy to EC2 (pull on server)

on:
  push:
    branches: [ main ]   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            REPO="https://github.com/sandeepvilla1612/Subway-Surfers_Fork.git"
            BRANCH="${{ secrets.BRANCH || 'main' }}"
            TARGET_DIR="/var/www/subway"
            DEPLOY_USER=$(whoami)

            sudo apt-get update -y
            sudo apt-get install -y git nginx

            if [ ! -d "${TARGET_DIR}/.git" ]; then
              sudo mkdir -p "${TARGET_DIR}"
              sudo chown -R ${DEPLOY_USER}:${DEPLOY_USER} "${TARGET_DIR}"
              git clone --depth 1 --branch "${BRANCH}" "${REPO}" "${TARGET_DIR}"
            else
              cd "${TARGET_DIR}"
              git fetch --all --prune
              git checkout "${BRANCH}" || true
              git reset --hard "origin/${BRANCH}"
            fi

            sudo chown -R ${DEPLOY_USER}:${DEPLOY_USER} "${TARGET_DIR}"

            # Nginx site config
            sudo tee /etc/nginx/sites-available/subway > /dev/null <<'NGINX'
server {
    listen 80;
    server_name _;
    root /var/www/subway;
    index game.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
NGINX

            sudo ln -sf /etc/nginx/sites-available/subway /etc/nginx/sites-enabled/subway
            sudo rm -f /etc/nginx/sites-enabled/default || true
            sudo nginx -t
            sudo systemctl reload nginx
