name: Deploy to EC2 (rsync from Actions)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) run build step if you had one. This repo is static so you can skip build.
      # - name: Build
      #   run: npm ci && npm run build

      - name: Setup deploy key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

      - name: Rsync files to server
        run: |
          rsync -avz --delete --exclude='.git' -e "ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./ ubuntu@${{ secrets.EC2_HOST }}:/var/www/subway/

      - name: Reload nginx on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: sudo systemctl reload nginx
